# Numerical Python(Numpy) - Part 1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np

In [2]:
a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
list(map(lambda x: 3*x, a))

[3, 6, 9]

In [4]:
b = np.array([1,2,3])
b*3

array([3, 6, 9])

## 1. Numpy Dimensional Array

In [5]:
a = np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype, a.shape

(dtype('float64'), (4,))

## 2. Array shape

In [21]:
# Vector (1차원)
vector = np.array([1,4,5,8])
vector.shape

(4,)

In [14]:
# Matrix (2차원)
matrix = np.array([[1,2,3], [4,5,16]])
print(matrix.shape)
print(matrix)

(2, 3)
[[ 1  2  3]
 [ 4  5 16]]


In [15]:
# Tensor (3차원 이상)
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
tensor

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [16]:
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [22]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [23]:
vector.size, matrix.size, tensor.size       # size : 원소의 갯수

(4, 6, 24)

In [24]:
# data type
# float32 : 32bit로 표시 - single precision
# float64 : 64bit로 표시 - double precision
a = np.array([1,2,3], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

In [25]:
b = np.array([1,2,3], dtype=np.int16)
b

array([1, 2, 3], dtype=int16)

### reshape

In [26]:
matrix.shape

(2, 3)

In [27]:
matrix.reshape(6,)

array([ 1,  2,  3,  4,  5, 16])

In [29]:
matrix.reshape(3,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5, 16]])

In [31]:
# -1 : size에 맞는 숫자로 알아서 넣어줌
matrix.reshape(-1,)

array([ 1,  2,  3,  4,  5, 16])

In [33]:
matrix.reshape(-1,2)        # size가 6이었으므로 -1 자리에 3이 들어감

array([[ 1,  2],
       [ 3,  4],
       [ 5, 16]])

In [34]:
matrix.reshape(3,-1).shape

(3, 2)

In [36]:
tensor.reshape(4,-1).shape

(4, 6)

### flatten

In [49]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [38]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

### Indexing

In [40]:
matrix.shape

(2, 3)

In [41]:
matrix

array([[ 1,  2,  3],
       [ 4,  5, 16]])

In [42]:
matrix[0][1]

2

In [43]:
matrix[0,1]

2

In [50]:
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [51]:
tensor[1,1,2]

19

### slicing

In [54]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
# 5,6,9,10
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [57]:
# 5,6,7, 9,10,11
b[1:3,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [59]:
# 1,3,9,11
b[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [63]:
# X는 앞에 3열, y는 마지막 열
X, y = b[:,:-1], b[:,-1]
X.shape, y.shape        # 2차원 이상은 대문자, 1차원은 소문자

((4, 3), (4,))