# 넘파이 연습문제

In [75]:
import numpy as np

### 1. 행렬 만들기

In [3]:
# 1번
a = np.arange(10,81,10).reshape(2,4)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2. 인덱싱, 슬라이싱

In [76]:
# 2번
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
# 2-1 이 행렬에서 값 7을 인덱싱한다.
print(m[1,2])

7


In [44]:
# 2-2 이 행렬에서 값 14를 인덱싱한다.
print(m[2,4])

14


In [45]:
# 2-3 이 행렬에서 배열 [6,7]을 슬라이싱 한다.
print(m[1,1:3])

[6 7]


In [77]:
# 2-4 이 행렬에서 배열 [7,12]를 슬라이싱 한다.
print(m[1:,2])

[ 7 12]


In [78]:
# 2-5 이 행렬에서 배열 [[3,4],[8,9]]를 슬라이싱 한다.
print(m[:2,3:])

[[3 4]
 [8 9]]


### Boolean Indexing

In [79]:
# 3번
# 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [83]:
# 3-1 이 배열에서 3의 배수를 찾아라.
print(f[f%3==0])

[ 0  3  6  9 12]


In [81]:
# 3-2 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
print(f[f%4==1])

[ 1  5  9 13]


In [84]:
# 3-3 이 배열에서 3으로 나누면 나누어 떨어지고 4로 나누면 1이 남는 수를 찾아라
f[np.logical_and(f%3==0, f%4==1)]

array([9])

### 4. eye로 행렬 만들기

In [52]:
# 4번
# 값을 직접 입력하지 말고 행렬 만들기
a = np.eye(5) * 2 + np.eye(5, k=1) + np.eye(5, k=-1) * 3
a

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

### 5. Matrix operation

In [86]:
# 5번
# 0에서 10까지 랜덤 실수값으로 이루어진 5X6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.
np.random.seed(2021)
m = np.random.uniform(0,10,30).reshape(5,6).round(4)
print(m)

[[6.0598 7.3337 1.3895 3.1267 9.9724 1.2816]
 [1.7899 7.5293 6.6216 7.8431 0.9689 0.5857]
 [9.624  6.1656 0.8663 5.6127 6.1652 9.6384]
 [5.743  3.7116 4.5215 2.0185 5.6931 1.951 ]
 [5.837  4.7631 5.1781 8.231  7.3223 0.6906]]


In [87]:
# 5-1 전체의 최댓값
np.max(m)

9.9724

In [88]:
# 5-2 각 행의 합
np.sum(m, axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [89]:
# 5-3 각 행의 최댓값
np.max(m, axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [90]:
# 5-4 각 열의 평균
np.mean(m, axis=0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

In [91]:
# 5-5 각 열의 최솟값
np.min(m, axis=0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

### 6. Sorting

In [92]:
# 6번
# 다음 배열은 첫번째 행에 학번, 두번째 행에 영어성적, 세번째 행에 수학성적을 적은 배열이다.
# 영어 성적을 기준으로 각 열을 재정렬하시오.
# array([[  1,  2,  3,  4],
#        [ 46, 99,100, 71],
#        [ 81, 59, 90,100]))

score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score


array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [94]:
np.sort(score)      # 이렇게 하면 안됨

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [95]:
s = np.argsort(score[1])
s

array([0, 3, 1, 2])

In [96]:
# 내림차순
s[::-1]

array([2, 1, 3, 0])

In [97]:
score[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [98]:
# 한 줄로
score[:,np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

### 7. 주사위 100번

In [99]:
# 7번
# 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.

np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [100]:
np.mean(dice)

3.7

In [101]:
np.unique(dice)         # 중복 제거

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 8번
# 가격이 10,000원인 주식이 있다.
# 이 주식의 일간 수익률은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자.
# 250일 동안의 주가를 무작위로 생성하시오.

